AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "[]"

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - jekyll-archive_link.gemspec

Naming/FileName:
  Exclude: [lib/jekyll-archive_link.rb]